---
- name: Install pip package
  apt:
    name:
      - python3-pip
      - python3-setuptools
    state: latest

- name: Install docker packages
  pip:
    name:
      - docker
      - docker-compose

- name: add docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repo key
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install docker package
  apt:
    name: "docker-ce"
    state: latest
    update_cache: true
