---
- name: spawn maildev container
  docker_container:
    name: maildev
    image: djfarrelly/maildev
    restart_policy: 'unless-stopped'
    ports:
      - "1080:80"
      - "1025:25"
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
